<ul class="simple">
  <li>
    <a onclick="javascript:ShowHide('HiddenDivWells')" href="javascript:;">Show/Hide</a>
    (<a href="https://code.launchpad.net/~dolfin-core/dolfin/wells">lp:~dolfin-core/dolfin/wells</a>)
  </li>
  <div class="mid" id="HiddenDivWells" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8081"
	    frameBorder="0" height="340"
	    width="100%"
	    align="center"
	    name="dolfin-wells">
      <a href="http://www.fenicsproject.org:8081">http://www.fenicsproject.org:8081</a>
    </iframe> 
  </div>
  <li>
    <a onclick="javascript:ShowHide('HiddenDivLogg')" href="javascript:;">Show/Hide</a>
    (<a href="https://code.launchpad.net/~dolfin-core/dolfin/logg">lp:~dolfin-core/dolfin/logg</a>)
  </li>
  <div class="mid" id="HiddenDivLogg" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8082"
	    frameBorder="0"
	    height="340"
	    width="100%"
	    align="center"
	    name="dolfin-logg">
      <a href="http://www.fenicsproject.org:8082">http://www.fenicsproject.org:8082</a>
    </iframe> 
  </div>
  <li>
    <a onclick="javascript:ShowHide('HiddenDivHake')" href="javascript:;" >Show/Hide</a>
    (<a href="https://code.launchpad.net/~dolfin-core/dolfin/hake">lp:~dolfin-core/dolfin/hake</a>)
  </li>
  <div class="mid" id="HiddenDivHake" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8083"
	    frameBorder="0"
	    height="340"
	    width="100%"
	    align="center"
	    name="dolfin-hake">
      <a href="http://www.fenicsproject.org:8083">http://www.fenicsproject.org:8083</a>
    </iframe> 
  </div>
  <li>
    <a onclick="javascript:ShowHide('HiddenDivRognes')" href="javascript:;">Show/Hide</a>
    (<a href="https://code.launchpad.net/~dolfin-core/dolfin/rognes">lp:~dolfin-core/dolfin/rognes</a>)
  </li>
  <div class="mid" id="HiddenDivRognes" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8084"
	    frameBorder="0"
	    height="340"
	    width="100%"
	    align="center"
	    name="dolfin-rognes">
      <a href="http://www.fenicsproject.org:8084">http://www.fenicsproject.org:8084</a>
    </iframe> 
  </div>
  <li>
    <a onclick="javascript:ShowHide('HiddenDivAlnes')" href="javascript:;">Show/Hide</a>
    (<a href="https://code.launchpad.net/~dolfin-core/dolfin/martinal">lp:~dolfin-core/dolfin/martinal</a>)
  </li>
  <div class="mid" id="HiddenDivAlnes" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8086"
	    frameBorder="0"
	    height="340"
	    width="100%"
	    align="center"
	    name="dolfin-alnes">
      <a href="http://www.fenicsproject.org:8086">http://www.fenicsproject.org:8086</a>
    </iframe> 
  </div>
  <li>
    <a onclick="javascript:ShowHide('HiddenDivMassing')" href="javascript:;">Show/Hide</a>
    (<a href="https://code.launchpad.net/~massing/dolfin/massing">lp:~massing/dolfin/massing</a>)
  </li>
  <div class="mid" id="HiddenDivMassing" style="DISPLAY: none" >
    <iframe src="http://www.fenicsproject.org:8087"
	    frameBorder="0"
	    height="340"
	    width="100%"
	    align="center"
	    name="dolfin-massing">
      <a href="http://www.fenicsproject.org:8087">http://www.fenicsproject.org:8087</a>
    </iframe> 
  </div>
</ul>
