<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

	<div id="front-block-1" class="front-block block">
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
        </div><!-- #front-block-1 .front-block .block-->

        <div id="front-block-2" class="front-block block">
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
          <h3>FEniCS lorem &mdash; Ipsum dolor sit amet!</h3>
          <img alt='' src='/new/_static/sample-news-image.png' class='avatar avatar-84 photo' height='84' width='84' />
	  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam varius consectetur purus, ac cursus sem ultricies sed. Suspendisse placerat commodo ante, sit amet aliquam risus dapibus sit amet.</p>
          <p><a href="/new/book/" rel="nofollow">Visit the project&#8217;s web site to learn more &raquo;</a></p>
        </div><!-- #front-block-2 .front-block .block-->

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
