<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h2>Anders Logg</h2>
          <div class="avatar mugshot">
	    <img alt='Anders Logg'
		 src='/_static/images/mugshots/logg.jpg' />
	  </div>
	  <p>Anders is a researcher
	  at <a href="http://simula.no/">Simula Research
	  Laboratory</a> and an adjunct professor at
	  the <a href="http://www.uio.no/">University of Oslo</a>.</p>
	  <p>He has been working on the FEniCS project since
	  2003. Apart from being the developer and maintainer of
	  several projects (including DOLFIN, FFC, UFC, CBC.Solve and
	  FEniCS Project web page), Anders has also coordinated several
	  FEniCS related activities over the years. You can view all Anders' contributions
          on <a href="https://launchpad.net/~logg">his Launchpad
          page.</a></p>
        </div>

      	<div class="front-block block">
  	  <h2>Marie Rognes</h2>
          <div class="avatar mugshot">
	    <img alt='Anders Logg'
		 src='/_static/images/mugshots/marie.jpg' />
	  </div>
	  <p>Marie is a postdoctoral fellow
	  at <a href="http://simula.no/">Simula Research 
	  Laboratory</a>.</p>
	  <p>She has been working on the FEniCS project since
	  2007. She is one of the developers of FIAT, FFC, UFL, DOLFIN
	  and the lead developer of ASCoT</p>

	  You can view all Marie's contributions
          on <a href="https://launchpad.net/~meg-simula">her Launchpad
          page.</a></p>
        </div>

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
