<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div id="front-block-1" class="front-block block">

          <img alt='' src='/_static/images/mugshots/logg.jpg'
          class='avatar photo' height=150' width='100' style="border:
          solid 1px #666; margin-top: 40px; margin-right:20px;"/>
	  
  	  <h2>Anders Logg</h2>


	  <p>Anders is a researcher at <a href="">Simula Research
	  Laboratory</a> and an adjunct professor at
	  the <a href="">University of Oslo</a>.</p>

	  <p>He has been working on the FEniCS projects since
	  2003. Apart from being the developer and maintainer of
	  several projects (including DOLFIN, FFC, UFC, CBC.Solve and
	  FEniCS Project web page), Anders has also coordinated several
	  FEniCS related activities over the years. You can view all Anders' contributions
          on <a href="https://launchpad.net/~logg">his Launchpad
          page.</a></p>

        </div><!-- #front-block-1 .front-block .block-->

        <div id="front-block-2" class="front-block block">

          <h3>CBC.Solve &mdash; A collection of Python solvers</h3>
          <img alt='' src='/_static/images/cbc_solve.png'
          class='avatar avatar-84 photo' height='84' width='84' />

	  <p>CBC.Solve is a collection of FEniCS based solvers
	     developed at the <a href="http://cbc.simula.no">Center
	     for Biomedical Computing</a> hosted
	     by <a href="http://www.simula.no">Simula Research
	     Laboratory</a> in Oslo. The current collection of solvers
	     includes CBC.Flow (Navier-Stokes), CBC.Twist
	     (hyperelasticity), CBC.Swing (fluid-structure
	     interaction) and CBC.Beat (bidomain equations).
           </p>

          <p><a href="https://launchpad.net/cbc.solve" rel="nofollow">Visit the
          project&#8217;s web site to learn more &raquo;</a></p>

        </div><!-- #front-block-2 .front-block .block-->

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
