<p style="text-align:center;">
  <a href="/download/debian_details.html"><img src="/_images/debian_large.png" alt="Download for Debian"></A>
  <a href="/download/ubuntu_details.html"><img src="/_images/ubuntu_large.png" alt="Download for Ubuntu"></A>
  <a href="/download/osx_details.html"><img src="/_images/mac_large.png" alt="Download for OS X"></A>
  <a href="/download/windows_details.html"><img src="/_images/windows_large.png" alt="Download for Windows"></A>
</p>
