<div class="row">
<div class="container-fuild">
      <!--Row 1-->
      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Martin Sandve Alnæs</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
               <div class="mugshot2" alt='Martin Sandve Alnæs' style='background: url(/_static/images/mugshots/alnaes.jpg) no-repeat 50% 50%' ></div>
              </div>
            <div class="center-justified">
              <p>Martin is a postdoctoral fellow at <a
              href="http://simula.no/">Simula Research Laboratory</a>.
                    </p>

                    <p>He has been involved with the FEniCS Project since 2006,
                    is the main developer of UFL and SFC, and one of the
                    developers of UFC, Instant, SyFi and DOLFIN.</p>

              <p>You can view all Martin&#8217;s contributions on <a
                    href="https://bitbucket.org/martinal">his Bitbucket
                    page.</a></p>
            </div>
          </div>
      </div>

      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Jan Blechta</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
                 <div class="mugshot2" alt='Jan Blechta' style='background: url(/_static/images/mugshots/blechta.jpg) no-repeat 50% 50%' ></div>
              </div>
            </div>
            <div class="center-justified">
              <p>
              Jan is a PhD. student of
              <a href="http://mod.karlin.mff.cuni.cz/en/">Mathematical Modelling</a>
              at the
              <a href="http://www.mff.cuni.cz/to.en/">Charles University in Prague</a>.
              </p>
              <p>
              He has been involved with the FEniCS project since 2013 and is a
              developer and maintainer of DOLFIN and Instant.
              </p>
              <p>You can view all Jan&#8217;s contributions on <a
              href="https://bitbucket.org/blechta">his Bitbucket
              page.</a></p>
            </div>
      </div>

      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Johan Hake</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
                <div class="mugshot2" alt='Johan Hake' style='background: url(/_static/images/mugshots/hake.jpg) no-repeat 50% 50%' ></div>
              </div>
            </div>
            <div class="center-justified">  
              <p>Johan is a postdoctoral fellow at <a
              href="http://simula.no/">Simula Research Laboratory</a>.
                    </p>

                    <p>He has been involved with the FEniCS Project since 2007,
                    is a maintainer of the Python interface of DOLFIN, and is
                    a developer of Instant, UFC and FFC.</p>

              <p>You can view all Johans&#8217;s contributions on <a
                    href="https://bitbucket.org/johanhake">his Bitbucket
                    page.</a></p>
            </div>
      </div>
      <div class="clearfix visible-*-block"></div>
      <!--End of Row 1-->

      <!--Row 2 -->
      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Johan Hoffman</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
                <div class="mugshot2" alt='Johan Hoffman' style='background: url(/_static/images/mugshots/hoffman.jpg) no-repeat 50% 50%' ></div>
              </div>
            </div>
            <div class="center-justified">
              <p>Johan is a professor at the <a href="http://www.kth.se/">KTH Royal Institute of Technology</a>.
              </p>
              <p>He has been involved with the FEniCS Project since 2003
              and is a developer of DOLFIN and Unicorn.</p>
            </div>
      </div>

      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Johan Jansson</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
                <div class="mugshot2" alt='Johan Jansson' style='background: url(/_static/images/mugshots/jansson.jpg) no-repeat 50% 50%' ></div>
              </div>
            </div>
            <div class="center-justified">
              <p>Johan is a senior researcher at the <a href="http://www.kth.se/">KTH Royal Institute of
              Technology</a>.</p>

              <p>He has been involved with the FEniCS Project since 2004
                and is a developer of DOLFIN and Unicorn.</p>
            </div>
      </div>

      <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
            <h4 align="center"><strong>Benjamin Kehlet</strong></h4>
            <div class="row" align="center">
              <div class="image-cropper">
                <div class="mugshot2" alt='Benjamin Kehlet' style='background: url(/_static/images/mugshots/kehlet.jpg) no-repeat 50% 50%' ></div>
              </div>
            </div>
            <div class="center-justified">  
              <p>Benjamin is a Ph.D. student at
                    <a href="http://www.simula.no/">Simula Research Laboratory</a> and the
                    <a href="http://www.uio.no/">University of Oslo</a>.
                    </p>

                    <p>He has been involved with the FEniCS Project since 2011
                    and is the primary developer of msrh, the FEniCS meshing component.
                    </p>

              <p>You can view all Benjamin&#8217;s contributions on <a
                    href="https://bitbucket.org/kehlet">his Bitbucket
                    page.</a></p>
            </div>
      </div>
      <div class="clearfix visible-*-block"></div>
      <!--End of Row 2-->

    <!--Row 3-->
    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Robert C. Kirby</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Robert C. Kirby' style='background: url(/_static/images/mugshots/kirby.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Robert is an associate professor at
            <a href="http://www.baylor.edu/">Baylor University</a>.
            </p>

            <p>He has been involved with the FEniCS Project since 2003
            and is the main developer of FIAT.</p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <a href="http://www.math.chalmers.se/~logg/"><h4 align="center"><strong>Anders Logg</strong></h4></a>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Anders Logg' style='background: url(/_static/images/mugshots/logg.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Anders is a professor at the
            <a href="http://www.chalmers.se/en/departments/math/Pages/default.aspx">Department of Mathematical Sciences</a> at
            <a href="http://www.chalmers.se/en/">Chalmers University of Technology</a>.

            <p>He has been involved with the FEniCS project since 2003
            and is a developer and maintainer of DOLFIN, FFC, UFC, UFL,
            CBC.Solve, Exterior and the FEniCS Project web page.</p>

            <p>You can view all Anders' contributions on <a
            href="https://bitbucket.org/logg">his Bitbucket
            page.</a></p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Kent-Andre Mardal</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Kent-Andre Mardal' style='background: url(/_static/images/mugshots/mardal.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">  
             <p>Kent is a senior research scientist at <a
                href="http://simula.no/">Simula Research Laboratory</a> and
                an adjunct associate professor at the <a
                href="http://www.uio.no/">University of Oslo</a>.</p>

                      <p>He has been involved with the FEniCS Project since 2006
                and is a developer of DOLFIN, Instant, SyFi, Exterior,
                CBC.Block and UFC.</p>
          </div>
    </div>

    <div class="clearfix visible-*-block"></div>
    <!--End of Row3-->

    <!--Row4-->
    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Andre Massing</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Andre Massing' style='background: url(/_static/images/mugshots/massing.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Andre is a Ph.D. student at <a
            href="http://simula.no/">Simula Research Laboratory</a>.
                  </p>

                  <p>He has been involved with the FEniCS Project since 2009,
                  has developed the mesh intersection functionality in DOLFIN
                  and is the main developer of DOLFIN-OLM.</p>

            <p>You can view all Andre&#8217;s contributions on <a
                  href="https://bitbucket.org/massing">his Bitbucket
                  page.</a></p>
          </div>
    </div>
    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Harish Narayanan</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Harish Narayanan' style='background: url(/_static/images/mugshots/harish.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Harish is a postdoctoral fellow at <a
            href="http://simula.no/">Simula Research Laboratory</a>.
                  </p>

            <p>He has been involved with the FEniCS project since 2007
            and is the primary developer of Dorsal (the FEniCS build
            system), the FEniCS project web site and CBC.Twist (a
            general solid mechanics solver) distributed as part of
            CBC.Solve.</p>

            <p>You can view all Harish&#8217;s contributions on <a
                  href="https://bitbucket.org/harish">his Bitbucket
                  page.</a></p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Chris Richardson</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Chris Richardson' style='background: url(/_static/images/mugshots/chris_richardson.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">  
              <p>Chris is a Computer Officer at <a
              href="http://www.bpi.cam.ac.uk/">BPI, University of Cambridge</a>.</p>

              <p>He has been involved with the FEniCS Project since 2012,
                 working mostly on Mesh and I/O improvements in parallel for HPC.</p>

              <p>You can view all Chris' contributions on <a
                    href="https://bitbucket.org/chris_richardson">his Bitbucket
                    page.</a></p>
          </div>
    </div>
    <div class="clearfix visible-*-block"></div>
  <!--End of Row4-->

      <!--Row5-->
    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Johannes Ring</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Johannes Ring' style='background: url(/_static/images/mugshots/ring.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Johannes is a research engineer at <a
            href="http://simula.no/">Simula Research Laboratory</a>.</p>

                  <p>He has been involved with the FEniCS Project since 2008,
                  mostly as a build engineer.</p>

            <p>You can view all Johannes' contributions on <a
                  href="https://bitbucket.org/johannes_ring">his Bitbucket
                  page.</a></p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Marie Rognes</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Marie Rognes' style='background: url(/_static/images/mugshots/rognes.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
            <p>Marie is a postdoctoral fellow at <a
            href="http://simula.no/">Simula Research Laboratory</a>.</p>

            <p>She has been involed with the FEniCS Project since 2007,
            is a developer of FIAT, FFC, UFL, DOLFIN
            and the lead developer of ASCoT.</p>

            <p>You can view all Marie&#8217;s contributions on <a
                  href="https://bitbucket.org/meg">her Bitbucket
                  page.</a></p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Kristoffer Selim</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Kristoffer Selim' style='background: url(/_static/images/mugshots/selim.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">  
            <p>Kristoffer is a postdoctoral fellow at the <a
              href="http://www.ffi.no/">Norwegian Defence Research Establishment</a>.
            </p>

            <p>He has been involved with the FEniCS Project since 2008 and
            is one of the developers of the fluid-structure interaction
            solver CBC.Swing distributed as part of CBC.Solve.</p>
          </div>
    </div>
    <div class="clearfix visible-*-block"></div>
  <!--End of Row5-->

  <!--Row6-->
    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Ridgway Scott</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Ridgway Scott' style='background: url(/_static/images/mugshots/scott.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
          <p>Ridgway is a professor at the <a href="http://cs.uchicago.edu/">University of Chicago</a>.
          </p>

          <p>He has been involved with the FEniCS Project since 2003.</p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Garth N. Wells</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Garth N. Wells' style='background: url(/_static/images/mugshots/wells.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">
         <p>Garth is the Hibbit Reader in Solid Mechanics at the
          <a href="http://www.eng.cam.ac.uk/">Department of Engineering</a>,
          University of Cambridge.</p>

          <p>He has been involved with the FEniCS project since 2005
          and is a developer and maintainer of DOLFIN, FFC, UFC and
          UFL.</p>

          <p>You can view all Garth's contributions on <a
          href="https://bitbucket.org/garth-wells">his Bitbucket
          page.</a></p>
          </div>
    </div>

    <div class="col-sm-12 col-xs-12 col-md-6 col-lg-4">  
          <h4 align="center"><strong>Kristian Breum Ølgaard</strong></h4>
          <div class="row" align="center">
            <div class="image-cropper">
              <div class="mugshot2" alt='Kristian Breum Ølgaard' style='background: url(/_static/images/mugshots/oelgaard.jpg) no-repeat 50% 50%' ></div>
            </div>
          </div>
          <div class="center-justified">  
            <p>Kristian is a research assistant at <a
            href="http://en.esbjerg.aau.dk/">Aalborg University</a>.
                  </p>

                  <p>He has been involved with the FEniCS Project since 2006,
                  is one of the main developers of FFC and FEniCS Plasticity, and a
                  developer of UFL and DOLFIN.</p>

            <p>You can view all Kristian&#8217;s contributions on <a
                  href="https://bitbucket.org/k-b-oelgaard">his Bitbucket
                  page.</a></p>
          </div>
    </div>
    <div class="clearfix visible-*-block"></div>
  <!--End of Row6-->
</div>
</div>