<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">

      	<div class="front-block block">
  	  <h2>Anders Logg</h2>
          <div class="avatar mugshot">
	    <img alt='Anders Logg'
		 src='/_static/images/mugshots/logg.jpg' />
	  </div>

          <p>Anders is a senior research scientist at <a
          href="http://simula.no/">Simula Research Laboratory</a> and
          an adjunct associate professor at the <a
          href="http://www.uio.no/">University of Oslo</a>.</p>

          <p>He has been involved with the FEniCS project since 2003
          and is developer and maintainer of DOLFIN, FFC, UFC, UFL,
          CBC.Solve, Exterior and the FEniCS Project web page.</p>

          <p>You can view all Anders' contributions on <a
          href="https://launchpad.net/~logg">his Launchpad
          page.</a></p>

        </div>

      	<div class="front-block block">
  	  <h2>Kent-Andre Mardal</h2>
          <div class="avatar mugshot">
	    <img alt='Kent-Andre Mardal'
		 src='/_static/images/mugshots/kent.jpg' />
	  </div>

	  <p>Kent is a senior research scientist at <a
	  href="http://simula.no/">Simula Research Laboratory</a> and
	  an adjunct associate professor at the <a
	  href="http://www.uio.no/">University of Oslo</a>.</p>

          <p>He has been involved with the FEniCS Project since 2006
	  and is a developer of DOLFIN, Instant, SyFi, Exterior,
	  CBC.Block and UFC.</p>

          <p>You can view all Kent's contributions on <a
          href="https://launchpad.net/~kent-and">his Launchpad
          page.</a></p>

        </div>

      	<div class="front-block block">
  	  <h2>Marie Rognes</h2>
          <div class="avatar mugshot">
	    <img alt='Marie Rognes'
		 src='/_static/images/mugshots/marie.jpg' />
	  </div>

	  <p>Marie is a postdoctoral fellow at <a
	  href="http://simula.no/">Simula Research Laboratory</a>.</p>

	  <p>She has been involed with the FEniCS Project since 2007,
	  is a developer of FIAT, FFC, UFL, DOLFIN
	  and the lead developer of ASCoT.</p>

	  <p>You can view all Marie's contributions on <a
          href="https://launchpad.net/~meg-simula">her Launchpad
          page.</a></p>

        </div>

      	<div class="front-block block">
  	  <h2>Johannes Ring</h2>
          <div class="avatar mugshot">
	    <img alt='Johannes Ring'
		 src='/_static/images/mugshots/ring.jpg' />
	  </div>

	  <p>Johannes is a research engineer at <a
	  href="http://simula.no/">Simula Research Laboratory</a>.</p>

          <p>He has been involved with the FEniCS Project since 2008,
          mostly as a build engineer.</p>

	  <p>You can view all Johannes' contributions on <a
          href="https://launchpad.net/~johannr">his Launchpad
          page.</a></p>

        </div>

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
