#!/bin/sh

echo "Publish script disabled after switch to new Wordpress pages."

#chmod +x build/html/index.html
#rsync -avz build/html/ fenics-web@fenicsproject.org:/home/fenics-web/fenicsproject.org/
