#!/bin/sh
#
# Copyright (C) 2010 Anders Logg.
# Licensed under the GNU LGPL version 3 or any later version.
#
# First added:  2011-04-15
# Last changed: 2011-05-01
#
# This script updates the sources for all relevant packages by pulling
# from Launchpad into a temporary directory. This script should be run
# before all other scripts to make sure that the documentation is
# based on the latest sources.

# List of packages
PACKAGES="dolfin ffc ufl"

# Location of sources
SOURCE_DIR="tmp/sources"

# Create temporary directory
mkdir -p $SOURCE_DIR

# Update all packages
cd $SOURCE_DIR
for PACKAGE in $PACKAGES; do
    if [ -d $PACKAGE ]; then
        echo "Found sources for package $PACKAGE, updating from Launchpad..."
        cd $PACKAGE
        bzr merge
        bzr commit -m merge
        cd ..
    else
        echo "Sources for package $PACKAGE does not exist, cloning from Launchpad..."
        bzr clone lp:$PACKAGE
    fi
done

# Display a message
echo
echo "Updated all sources in $SOURCE_DIR"
