<div id="leader">
  <div id="leader-container">
    <div id="feature">

      <!--- Featured item --->
      <a href="http://www.fenicsproject.org/new/featured/2011/fenics_1beta"><img src="/new/_static/images/featured_item_fenics_1beta.png" alt="FEniCS 1.0 beta"/></a>

      <div id="feature-info">
        <!--<h2 style="margin-top:0;">Mathematical physics can be fun!</h2>-->

        <p>The FEniCS Project is a collection of
          <a href="http://www.gnu.org/philosophy/free-sw.html">free
        software</a> aimed at automated, efficient solution of
        differential equations.</p>

	<p>Through this web site, you can <a href="/new/about">learn
	more about the project</a> and
	learn <a href="/new/download">how to obtain</a>
	and <a href="/new/documentation">how to use</a> our
	software. We'd be delighted to offer support in case you need
	it, and encourage contributions from our users.</p>

	<a href="/new/download/"><img style="width: 300px; margin-left:40px; margin-top:10px;" src="/new/_static/download-button.png" alt="Download button" /></a>

      </div><!-- #feature-info -->
      <div class="clear-block"></div>
    </div><!-- #feature -->
  </div><!-- #leader-container -->
</div><!-- #leader -->

<div id="main">
  <div id="container" class="feature">
    <div id="content">
      <div id="sub-feature">
	<div id="front-block-1" class="front-block block">

          <h3>FEniCS book about to be released!</h3>
          <img alt='' src='/new/_static/images/genericbook.png' class='avatar avatar-84 photo' width='84'/>

	  <p>The FEniCS book project is nearing completion. The book,
            titled <i>Automated Solution of Differential Equations by
            the Finite Element Method</i>, will be published as part
            of the Springer Lecture Notes in Computational Science and
            Engineering in the fall of 2011.
          </p>

          <p><a href="/new/book" rel="nofollow">Find out more about
          the book project &raquo;</a></p>

          <h3>Who's behind the FEniCS Project?</h3>
          <img alt='' src='/new/_static/images/fenicsworld.png' class='avatar avatar-84 photo' height='84' width='84' />

	  <p>The FEniCS Project is a collaborative effort between
	  research groups from Simula Research Laboratory, University
	  of Cambridge, University of Chicago, Texas Tech University
	  and KTH Royal Institute of Technology.
            </p>

          <p><a href="/new/about/" rel="nofollow">Find out more about
          our project &raquo;</a></p>

        </div><!-- #front-block-1 .front-block .block-->

        <div id="front-block-2" class="front-block block">
          <h3>Recent project news <a href="/new/_static/news/feed.xml" title="The FEniCS Project News RSS feed" rel="alternate nofollow" type="application/rss+xml"><img src="/new/_static/feed-icon-14x14.gif" alt="RSS"/></a></h3>
	  <!--#include virtual="_static/news/include.html"-->
        </div><!-- #front-block-2 .front-block .block-->

      </div><!-- #sub-feature -->
    </div><!-- #content -->
  </div><!-- #container .feature -->
</div><!-- #main -->
