<div id="leader"> 
        <div id="leader-container"> 
 
<div id="feature"> 
 
  <a href="http://localhost:8888/"><img src="http://localhost:8888/wp-content/themes/thematicfeaturesite/includes/images/feature-item-1.png" alt="A look at the Thematic WordPress Theme"/></a> 
  
    <div id="feature-info"> 
              
        <h2>Mathematical physics can be fun!</h2> 
        <p>The FEniCS Project is a collection of free software aimed at automated, efficient solution of differential equations. The project provides tools for working with computational meshes, finite element variational formulations of PDEs, ODE solvers and linear algebra.</p> 
     <p>Through this web site, you can learn more about the project and learn how to obtain and use our software. We'd be delighted to offer support in case you need it, and encourage contributions from our users.</em></p> 
        <div id="buttons"> 
            <a href="http://localhost:8888/obtaining/" class="button" rel="nofollow">Download!</a> 
            <a href="http://localhost:8888/about/" class="button">Learn more...</a> 
        </div> 
    
    </div><!-- #feature-info --> 
 
<div class="clear-block"></div> 
  
</div><!-- #feature --> 
 
        </div><!-- #leader-container --> 
    </div><!-- #leader --> 

    <div id="main"> 
    
	<div id="container" class="feature"> 
		<div id="content">		
		  <div id="sub-feature"> 
 
            <div id="front-block-1" class="front-block block">  
              <h3>FEniCS book about to be released!</h3> 
              <img alt='' src='' class='avatar avatar-84 photo' height='84' width='84' />              <p>The FEniCS Project will be releasing its first book in late 2010. This book will feature blah, blah and blah. The FEniCS Project will be releasing its first book in late 2010. Yes, really. Content on the front page can be modified by touching <tt>front-page.php</tt>. It is not open to be tampered with by random passers by.</p> 
              <p><a href="http://localhost:8888/about/" rel="nofollow">Find out more about the book project&raquo;</a></p> 
              <h3>Who's behind the FEniCS project?</h3> 
              <img alt='' src='' class='avatar avatar-84 photo' height='84' width='84' />              <p>The FEniCS Project is a collaborative open source effort. In chronological order, its contributors include the University of Chicago, Argonne National Laboratory, Delft University of Technology, Royal Institute of Technology KTH, Simula Research Laboratory, Texas Tech University, and University of Cambridge.</p> 
              <p><a href="http://localhost:8888/about/" rel="nofollow">Find out more about our project&raquo;</a></p> 
            </div><!-- #front-block-1 .front-block .block--> 
            
            <div id="front-block-2" class="front-block block">  
              <h3>Recent project news <a href="/news/feed/" title="The FEniCS Project Posts RSS feed" rel="alternate nofollow" type="application/rss+xml"><img src="http://localhost:8888/wp-content/themes/thematicfeaturesite/images/feed-icon-14x14.gif" alt="RSS"/></a></h3> 
              <ul id="recent-items"> 
              <li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="FEniCS Project Announcements icon"> 
<a href="https://launchpad.net/fenics/+announcement/8369">2011-05-18: Mac OS X and Windows binaries updated</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="Instant Announcements icon"> 
<a href="https://launchpad.net/instant/+announcement/8364">2011-05-16: Instant 0.9.10</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="UFL Announcements icon"> 
<a href="https://launchpad.net/ufl/+announcement/8363">2011-05-16: UFL 0.9.1</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/dolfin.png" width="14" height="14" alt="DOLFIN Announcements icon"> 
<a href="https://launchpad.net/dolfin/+announcement/8362">2011-05-16: DOLFIN 0.9.11</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="FFC Announcements icon"> 
<a href="https://launchpad.net/ffc/+announcement/8361">2011-05-16: FFC 0.9.10</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="UFC Announcements icon"> 
<a href="https://launchpad.net/ufc/+announcement/8360">2011-05-16: UFC 2.0.1</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="FFC Announcements icon"> 
<a href="https://launchpad.net/ffc/+announcement/8357">2011-05-16: Simplex quadrature improvements</a> 
</li> 
<li> 
<img class="avatar" src="/images/project-icons/unknown.png" width="14" height="14" alt="The FEniCS-Apps Project Announcements icon"> 
<a href="https://launchpad.net/unicorn/+announcement/8253">2011-04-29: Unicorn HPC 0.1.2</a> 
</li> 
              <li class="more-items"><a href="/news/">More recent items</a></li> 
              </ul> 
            </div><!-- #front-block-2 .front-block .block--> 
          
          </div><!-- #sub-feature -->         
		</div><!-- #content --> 
	</div><!-- #container .feature --> 
 
 
    </div><!-- #main -->
