<div class="fetched-news">


<div class="news-item">
<div class="title"><a href="https://launchpad.net/unicorn/+announcement/8253">: apps: Unicorn HPC 0.1.2</a></div>
<div class="author"></div>
<div class="date">April 29, 2011 10:07 PM</div>
<div class="content"><p>A new version of Unicorn has been released. This release fixes various bugs and portability issues.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dorsal/+announcement/7870">: dorsal: Dorsal 0.8.2 Released!</a></div>
<div class="author"></div>
<div class="date">February 28, 2011 02:48 PM</div>
<div class="content"><p>This is a bug-fix release that makes sure all the packages are up-to-date.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dolfin/+announcement/7847">: dolfin: DOLFIN 0.9.10</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 09:26 PM</div>
<div class="content"><p>A new version of DOLFIN has been released. This release adds a large number of improvements and bug fixes, most notably improved parallel scaling and experimental support for multi-core computing.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/instant/+announcement/7846">: instant: Instant 0.9.9</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 09:07 PM</div>
<div class="content"><p>A new version of Instant has been released. This version brings speed improvements to JIT compilation.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/fenics-viper/+announcement/7845">: viper: Viper 0.4.7</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 08:41 PM</div>
<div class="content"><p>A new version of Viper has been released. This version contains a number of small fixes/improvements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufl/+announcement/7844">: ufl: UFL 0.9.0</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 08:33 PM</div>
<div class="content"><p>A new version of UFL has been released. This release fixes some minor bugs.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ffc/+announcement/7842">: ffc: FFC 0.9.9</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 07:42 PM</div>
<div class="content"><p>A new version of FFC has been released. This version adds support for UFC 2.0 and plotting of elements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufc/+announcement/7841">: ufc: UFC 2.0.0</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 06:33 PM</div>
<div class="content"><p>A new version of UFC has been released. This version adds new functionality to the UFC interface and makes some minor modifications to the existing UFC interface.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/unicorn/+announcement/7703">: apps: Unicorn HPC 0.1.1</a></div>
<div class="author"></div>
<div class="date">February 04, 2011 07:36 AM</div>
<div class="content"><p>A new version of Unicorn has been released. This release adds support for parallel elastic smoothing, adaptive projection and fixes various bugs and portability issues. It also adds support for the new Cray XE6 platform.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/fenics/+announcement/7535">: fenics: Windows installer now available</a></div>
<div class="author"></div>
<div class="date">January 07, 2011 03:08 PM</div>
<div class="content"><p>A binary installer for Windows users is now available for download from the installation page at <a href="http://www.fenicsproject.org" rel="nofollow">http://&lt;wbr&gt;&lt;/wbr&gt;www.fenicsproje&lt;wbr&gt;&lt;/wbr&gt;ct.org</a>. It includes everything necessary to run FEniCS on Windows and runs on XP, Vista, and on Windows 7.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/unicorn/+announcement/8253">apps: Unicorn HPC 0.1.2</a></div>
<div class="author"></div>
<div class="date">April 29, 2011 10:07 PM</div>
<div class="content"><p>A new version of Unicorn has been released. This release fixes various bugs and portability issues.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dorsal/+announcement/7870">dorsal: Dorsal 0.8.2 Released!</a></div>
<div class="author"></div>
<div class="date">February 28, 2011 02:48 PM</div>
<div class="content"><p>This is a bug-fix release that makes sure all the packages are up-to-date.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dolfin/+announcement/7847">dolfin: DOLFIN 0.9.10</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 09:26 PM</div>
<div class="content"><p>A new version of DOLFIN has been released. This release adds a large number of improvements and bug fixes, most notably improved parallel scaling and experimental support for multi-core computing.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/instant/+announcement/7846">instant: Instant 0.9.9</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 09:07 PM</div>
<div class="content"><p>A new version of Instant has been released. This version brings speed improvements to JIT compilation.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/fenics-viper/+announcement/7845">viper: Viper 0.4.7</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 08:41 PM</div>
<div class="content"><p>A new version of Viper has been released. This version contains a number of small fixes/improvements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufl/+announcement/7844">ufl: UFL 0.9.0</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 08:33 PM</div>
<div class="content"><p>A new version of UFL has been released. This release fixes some minor bugs.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ffc/+announcement/7842">ffc: FFC 0.9.9</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 07:42 PM</div>
<div class="content"><p>A new version of FFC has been released. This version adds support for UFC 2.0 and plotting of elements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufc/+announcement/7841">ufc: UFC 2.0.0</a></div>
<div class="author"></div>
<div class="date">February 23, 2011 06:33 PM</div>
<div class="content"><p>A new version of UFC has been released. This version adds new functionality to the UFC interface and makes some minor modifications to the existing UFC interface.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/unicorn/+announcement/8253">Unicorn HPC 0.1.2</a></div>
<div class="author">Niclas Jansson</div>
<div class="date">April 29, 2011 10:07 PM</div>
<div class="content"><p>A new version of Unicorn has been released. This release fixes various bugs and portability issues.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dorsal/+announcement/7870">Dorsal 0.8.2 Released!</a></div>
<div class="author">Harish Narayanan</div>
<div class="date">February 28, 2011 02:48 PM</div>
<div class="content"><p>This is a bug-fix release that makes sure all the packages are up-to-date.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dolfin/+announcement/7847">DOLFIN 0.9.10</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 09:26 PM</div>
<div class="content"><p>A new version of DOLFIN has been released. This release adds a large number of improvements and bug fixes, most notably improved parallel scaling and experimental support for multi-core computing.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/instant/+announcement/7846">Instant 0.9.9</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 09:07 PM</div>
<div class="content"><p>A new version of Instant has been released. This version brings speed improvements to JIT compilation.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/fenics-viper/+announcement/7845">Viper 0.4.7</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 08:41 PM</div>
<div class="content"><p>A new version of Viper has been released. This version contains a number of small fixes/improvements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufl/+announcement/7844">UFL 0.9.0</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 08:33 PM</div>
<div class="content"><p>A new version of UFL has been released. This release fixes some minor bugs.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ffc/+announcement/7842">FFC 0.9.9</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 07:42 PM</div>
<div class="content"><p>A new version of FFC has been released. This version adds support for UFC 2.0 and plotting of elements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufc/+announcement/7841">UFC 2.0.0</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 06:33 PM</div>
<div class="content"><p>A new version of UFC has been released. This version adds new functionality to the UFC interface and makes some minor modifications to the existing UFC interface.</p></div>
</div>


</div>
