<div class="fetched-news">

<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="FEniCS Project Announcements icon">
<a href="https://launchpad.net/fenics/+announcement/8369">May 18, 2011 03:17 PM: Mac OS X and Windows binaries updated</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="Instant Announcements icon">
<a href="https://launchpad.net/instant/+announcement/8364">May 16, 2011 04:41 PM: Instant 0.9.10</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="UFL Announcements icon">
<a href="https://launchpad.net/ufl/+announcement/8363">May 16, 2011 04:40 PM: UFL 0.9.1</a>
</li>
<li>
<img class="avatar" src="_static/dolfin.png" width="14" height="14" alt="DOLFIN Announcements icon">
<a href="https://launchpad.net/dolfin/+announcement/8362">May 16, 2011 04:38 PM: DOLFIN 0.9.11</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="FFC Announcements icon">
<a href="https://launchpad.net/ffc/+announcement/8361">May 16, 2011 04:37 PM: FFC 0.9.10</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="UFC Announcements icon">
<a href="https://launchpad.net/ufc/+announcement/8360">May 16, 2011 04:35 PM: UFC 2.0.1</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="FFC Announcements icon">
<a href="https://launchpad.net/ffc/+announcement/8357">May 16, 2011 10:18 AM: Simplex quadrature improvements</a>
</li>
<li>
<img class="avatar" src="_static/unknown.png" width="14" height="14" alt="The FEniCS-Apps Project Announcements icon">
<a href="https://launchpad.net/unicorn/+announcement/8253">April 29, 2011 10:07 PM: Unicorn HPC 0.1.2</a>
</li>
<li>
<img class="avatar" src="_static/dorsal.png" width="14" height="14" alt="Dorsal Announcements icon">
<a href="https://launchpad.net/dorsal/+announcement/7870">February 28, 2011 02:48 PM: Dorsal 0.8.2 Released!</a>
</li>
<li>
<img class="avatar" src="_static/dolfin.png" width="14" height="14" alt="DOLFIN Announcements icon">
<a href="https://launchpad.net/dolfin/+announcement/7847">February 23, 2011 09:26 PM: DOLFIN 0.9.10</a>
</li>

</div>
