<div class="fetched-news">


<div class="news-item">
<div class="title"><a href="https://launchpad.net/fenics/+announcement/8369">Mac OS X and Windows binaries updated</a></div>
<div class="author">Johannes Ring</div>
<div class="date">May 18, 2011 03:17 PM</div>
<div class="content"><p>The Mac OS X and Windows binaries have been updated and now features DOLFIN 0.9.11, FFC 0.9.10, Instant 0.9.10, UFC 2.0.1 and UFL 0.9.1. They are available from the installation page at <a href="http://www.fenicsproject.org" rel="nofollow">http://&lt;wbr&gt;&lt;/wbr&gt;www.fenicsproje&lt;wbr&gt;&lt;/wbr&gt;ct.org</a>.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/instant/+announcement/8364">Instant 0.9.10</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 04:41 PM</div>
<div class="content"><p>A new version of Instant has been released. This version permits the SWIG executable to be set.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufl/+announcement/8363">UFL 0.9.1</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 04:40 PM</div>
<div class="content"><p>A new version of UFL has been released.  The release provides some new features, and a range of behind-the-scenes improvements. A list of changes can be found the in ChangeLog.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dolfin/+announcement/8362">DOLFIN 0.9.11</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 04:38 PM</div>
<div class="content"><p>A new version of DOLFIN has been released with a number of improvements and a significant number of bug fixes.  A comprehensive list of new features and bug fixes can be found in the ChangeLog.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ffc/+announcement/8361">FFC 0.9.10</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 04:37 PM</div>
<div class="content"><p>A new version of FFC has been released. This release makes optimised quadrature schemes for simplices available, and includes a number of behind-the-scenes improvements.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ufc/+announcement/8360">UFC 2.0.1</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 04:35 PM</div>
<div class="content"><p>A new version of UFC has been released.  With this release, UFC moves to SWIG version &gt;= 2.0. This release also fixes a const bug in the interface.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/ffc/+announcement/8357">Simplex quadrature improvements</a></div>
<div class="author">Garth Wells</div>
<div class="date">May 16, 2011 10:18 AM</div>
<div class="content"><p>The development version of FFC now provides optimised rules for quadrature on triangles and tetrahedra. The provides a performance boost when using the quadrature representation, especially for lower order forms.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/unicorn/+announcement/8253">Unicorn HPC 0.1.2</a></div>
<div class="author">Niclas Jansson</div>
<div class="date">April 29, 2011 10:07 PM</div>
<div class="content"><p>A new version of Unicorn has been released. This release fixes various bugs and portability issues.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dorsal/+announcement/7870">Dorsal 0.8.2 Released!</a></div>
<div class="author">Harish Narayanan</div>
<div class="date">February 28, 2011 02:48 PM</div>
<div class="content"><p>This is a bug-fix release that makes sure all the packages are up-to-date.</p></div>
</div>


<div class="news-item">
<div class="title"><a href="https://launchpad.net/dolfin/+announcement/7847">DOLFIN 0.9.10</a></div>
<div class="author">Anders Logg</div>
<div class="date">February 23, 2011 09:26 PM</div>
<div class="content"><p>A new version of DOLFIN has been released. This release adds a large number of improvements and bug fixes, most notably improved parallel scaling and experimental support for multi-core computing.</p></div>
</div>


</div>
